"""Generate fixed Q15 ringing filters; no measured amplitude template is used."""
from pathlib import Path
import numpy as np

FS = 240000
FREQUENCY = 6250
REFERENCE_DEG = 110
START, STOP = 20, 240
WINDOWS = [(20, 240), (20, 140), (100, 220)]


def coefficients():
    result = np.zeros((STOP - START, 6), dtype=np.int64)
    for k, (a, b) in enumerate(WINDOWS):
        t = np.arange(a, b) / FS
        trend = np.column_stack((np.ones(len(t)), (t - t.mean()) / np.ptp(t)))
        w = np.hanning(len(t))
        v = np.exp(-2j * np.pi * FREQUENCY * t - 1j * np.deg2rad(REFERENCE_DEG))
        v = w * (v - trend @ np.linalg.solve(trend.T @ (w[:, None] * trend), trend.T @ (w * v)))
        for part, values in enumerate((v.real, v.imag)):
            integers = np.rint(values * 32768 / w.sum()).astype(np.int64)
            integers[len(integers) // 2] -= integers.sum()  # exact DC rejection
            result[a-START:b-START, 2*k+part] = integers
    assert np.max(np.abs(result)) < 32768
    assert (np.abs(result).sum(axis=0) * 32768 < 2**31).all()
    assert (result.sum(axis=0) == 0).all()
    return result


if __name__ == '__main__':
    table = coefficients()
    target = Path(__file__).resolve().parents[1] / 'Core/Inc/rx_phase_coefficients.h'
    text = '/* Generated by HostTools/generate_rx_phase_coefficients.py. */\n'
    text += '#ifndef RX_PHASE_COEFFICIENTS_H\n#define RX_PHASE_COEFFICIENTS_H\n'
    text += '#include <stdint.h>\n'
    text += '/* Fs=240000 Hz, ringing=6250 Hz, fixed phase-zero axis=110 degrees.\n'
    text += ' * Columns: I,Q for full, early and late windows. Sum of each is zero. */\n'
    text += 'static const int16_t rx_phase_coefficients[220][6] = {\n'
    text += ''.join('    {' + ', '.join(map(str, row)) + '},\n' for row in table)
    text += '};\n#endif\n'
    target.write_text(text, encoding='utf-8')
    print(target)
